"""add User.ucid + snipe_scores table

Revision ID: 04643059de59
Revises: 6e1ac9482ec0
Create Date: 2026-05-02 15:25:22.894714+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04643059de59'
down_revision: str | None = '6e1ac9482ec0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snipe_scores',
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_discord_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_discord_id')
    )
    op.create_index('ix_snipe_scores_points', 'snipe_scores', ['points'], unique=False)
    op.add_column('users', sa.Column('ucid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ucid')
    op.drop_index('ix_snipe_scores_points', table_name='snipe_scores')
    op.drop_table('snipe_scores')
    # ### end Alembic commands ###
