"""add reminders table

Revision ID: 6e1ac9482ec0
Revises: 6f051e41caf1
Create Date: 2026-05-01 16:51:03.682292+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e1ac9482ec0'
down_revision: str | None = '6f051e41caf1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_discord_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_due_fired', 'reminders', ['due_at', 'fired'], unique=False)
    op.create_index(
        op.f('ix_reminders_user_discord_id'), 'reminders',
        ['user_discord_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_discord_id'), table_name='reminders')
    op.drop_index('ix_reminders_due_fired', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
