"""add lottery_entries table

Revision ID: 6f051e41caf1
Revises: b231e2ca853e
Create Date: 2026-05-01 16:46:42.794007+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f051e41caf1'
down_revision: str | None = 'b231e2ca853e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_entries',
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_discord_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_discord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottery_entries')
    # ### end Alembic commands ###
